### ISSUE TITLE
Bug: RouteAdd and Edit Notes  and AddNews

### ISSUE THREAD

**Issue by LugsoIn2** [POLYTALON/climbing-gym-app#365]
- Route Add and Edit and AddNews: 
     - every new word starts with a big letter (keyboard)
    - Notes and News Text Textfield - you can press only return (new line) on keyboard so you can't minimize the keyboard that hidden the Buttons.
Maybe we must resize the slidingUp Panel max height or add an Devider at the bottom?

**Comment by v1lling** [comment]
nicely done :)
